import Foundation

/// The rule that decides what follows what.
///
/// WHY THIS IS SEPARATE FROM THE ENGINE
/// Everything else about the timer involves a clock, a database and an alarm.
/// This does not: given the block that just ended and how the sprint stood, it
/// returns the next block. No time passes inside it, nothing is saved, nothing
/// can fail. That makes it the one part of the feature that can be proved
/// exhaustively by a handful of tests with no setup at all, and it is the part
/// most worth proving, because an off-by-one here is invisible until the
/// fourth pomodoro of the day.
///
/// It is an `enum` with no cases — a namespace holding one function, never an
/// instance of anything.
enum TimerCycle {
  /// What happens next.
  struct Transition: Equatable, Sendable {
    /// The block that follows.
    let kind: BlockKind

    /// How many focus blocks are complete in the sprint after this transition.
    let completedInSprint: Int

    /// True only when a long break has just ended.
    ///
    /// The engine returns to idle on this even when auto-start is switched on.
    /// Four pomodoros and a long break is a natural stopping point, and a
    /// timer that quietly starts a fifth block while you have walked away is a
    /// timer that fills your history with abandoned blocks generated by an
    /// empty room.
    let endsSprint: Bool
  }

  /// Returns the block that follows the one that just ended.
  ///
  /// THE COMPLETE RULE, IN WORDS
  ///
  ///   * A **completed focus block** counts: the sprint's tally goes up by
  ///     one. If that tally has reached the sprint size, the long break
  ///     follows; otherwise the short break does.
  ///   * A **skipped focus block** does not count. The short break follows and
  ///     the tally is unchanged — so skipping the fourth block of four leads to
  ///     a short break and then a fourth focus block again. The long break is
  ///     earned by four *finished* pomodoros, never by four attempts.
  ///   * A **break of either kind** is always followed by a focus block, and
  ///     never changes the tally. Breaks are not pomodoros.
  ///   * A **long break** ends the sprint: the tally returns to zero and
  ///     `endsSprint` is true.
  ///
  /// With the spec's defaults that produces: work, short, work, short, work,
  /// short, work, **long** — then a stop. With a sprint of one, finishing every
  /// block produces work, long, stop.
  ///
  /// A sprint of one does **not** mean a short break can never happen: skip the
  /// focus block instead of finishing it and a short break follows, there as
  /// anywhere else, because a skipped block earns nothing and the long break is
  /// earned rather than scheduled.
  ///
  /// - Parameters:
  ///   - kind: the block that has just ended.
  ///   - completedInSprint: how many focus blocks were complete before it ended.
  ///   - completed: false when the block was skipped or dismissed early.
  ///   - settings: the snapshot the ended block was started with. Only the
  ///     sprint size is read; it comes from the snapshot rather than from the
  ///     live settings so that changing the sprint size mid-block cannot
  ///     retroactively decide which break you have earned.
  static func next(
    after kind: BlockKind,
    completedInSprint: Int,
    completed: Bool,
    settings: TimerSettingsSnapshot
  ) -> Transition {
    switch kind {
    case .work:
      // A skipped focus block advances the cycle but earns nothing. Skipping
      // the fourth block of four therefore leads to a short break and then a
      // fourth focus block again, rather than to the long break.
      guard completed else {
        return Transition(kind: .shortBreak, completedInSprint: completedInSprint, endsSprint: false)
      }
      let tally = completedInSprint + 1
      // `>=` rather than `==` on purpose: if the sprint size is reduced while a
      // sprint is part-finished, the next completed block should end it rather
      // than run past a target it has already overshot.
      let earnedLongBreak = tally >= settings.pomodorosPerSprint
      return Transition(
        kind: earnedLongBreak ? .longBreak : .shortBreak,
        completedInSprint: tally,
        endsSprint: false)

    case .shortBreak:
      // Breaks are not pomodoros, so the tally does not move — whether the
      // break was taken in full or skipped.
      return Transition(kind: .work, completedInSprint: completedInSprint, endsSprint: false)

    case .longBreak:
      // The sprint is over. The tally resets and the engine returns to idle,
      // even with auto-start switched on.
      return Transition(kind: .work, completedInSprint: 0, endsSprint: true)
    }
  }
}
