#!/usr/bin/env bash
#
# Draw the ZenTomato app icon and write it into the asset catalog.
#
# WHY THE ICON IS DRAWN BY A SCRIPT
# This repository is public and GPL-3.0, which means everything it ships has to
# be something it can license onward. A stock photograph cannot be: the one
# originally chosen was an Unsplash+ image, whose licence is explicitly
# non-transferable and non-sublicensable, so putting it here would have made the
# repository's own licence a promise it could not keep.
#
# Drawing the icon instead makes it original work, GPL-clean, and — because the
# colours below are the Civic Data design tokens the app already uses — it makes
# the icon and the interface the same design rather than two that merely coexist.
#
# The vector source is the truth; the PNGs are build products of this script.
# Re-run it after any change:
#
#     ./Design/icon/make-icon.sh
#
# Needs `rsvg-convert` (brew install librsvg). It is NOT part of the build or of
# CI — the PNGs it produces are committed, so a clone builds without it.

set -euo pipefail

REPO_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)"
HERE="${REPO_ROOT}/Design/icon"
ICONSET="${REPO_ROOT}/ZenTomato/Resources/Assets.xcassets/AppIcon.appiconset"

command -v rsvg-convert >/dev/null 2>&1 || {
  echo "make-icon.sh: rsvg-convert is not installed." >&2
  echo "              brew install librsvg" >&2
  exit 1
}

mkdir -p "$HERE" "$ICONSET"

# --- The drawing -----------------------------------------------------------
# One tomato, flat, filling the frame. Three decisions worth stating:
#
#   NO GLOSS. An earlier pass had a highlight ellipse and it read as sticker
#   shine — wrong for a design language whose whole personality is flat shapes
#   and 2-6px corners. A shaded crescent was tried too and read as a second
#   overlapping circle rather than as form. Flat is the confident answer.
#
#   NO TIMER RING. A countdown ring around the tomato was legible at 1024px and
#   mush at 40px, which is the size that decides whether an icon works. The app
#   is called ZenTomato and a Pomodoro *is* a tomato; the fruit carries it.
#
#   STRAIGHT-EDGED CALYX. Five flat leaves with straight edges rather than an
#   organic curve. It is what stops this reading as a generic fruit sticker, and
#   it is the design system's geometry applied to something that is not a
#   rectangle.
draw() {
  local out="$1" ground="$2" body="$3" calyx="$4" stem="$5"
  cat > "${HERE}/${out}.svg" <<SVG
<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024">
  <!-- Generated by Design/icon/make-icon.sh — edit that, not this. -->
  <rect width="1024" height="1024" fill="${ground}"/>
  <circle cx="512" cy="580" r="352" fill="${body}"/>
  <g fill="${calyx}">
    <path d="M 512 150 L 512 300 L 350 236 Z"/>
    <path d="M 512 150 L 512 300 L 674 236 Z"/>
    <path d="M 512 176 L 512 316 L 386 356 Z"/>
    <path d="M 512 176 L 512 316 L 638 356 Z"/>
    <path d="M 512 196 L 452 330 L 512 344 L 572 330 Z"/>
  </g>
  <rect x="492" y="108" width="40" height="104" rx="6" fill="${stem}"/>
</svg>
SVG
  rsvg-convert -w 1024 -h 1024 "${HERE}/${out}.svg" -o "${ICONSET}/${out}.png"
}

# Colours are Civic Data tokens, the same values ZenTomato/DesignSystem uses.
#
#   light   stone50 ground, red600 body, sage700/800 calyx
#   dark    slate900 ground, and the accents LIGHTEN — red500 and sage400 —
#           for the same reason the app's dark theme lightens them: red600 on
#           slate is 2.3:1 and disappears.
#   tinted  greyscale. iOS derives the user's chosen tint from luminance, so
#           this variant carries no hue of its own; the values are spaced so the
#           calyx still separates from the body once a single hue is applied.
draw AppIcon-light  "#f6f5f2" "#c0392b" "#4c5c36" "#3f4c2d"
draw AppIcon-dark   "#1c1f22" "#e06a50" "#8aa163" "#667a49"
draw AppIcon-tinted "#ffffff" "#7d7d7d" "#242424" "#1a1a1a"

# --- The catalog entry -----------------------------------------------------
cat > "${ICONSET}/Contents.json" <<'JSON'
{
  "images" : [
    {
      "filename" : "AppIcon-light.png",
      "idiom" : "universal",
      "platform" : "ios",
      "size" : "1024x1024"
    },
    {
      "appearances" : [
        {
          "appearance" : "luminosity",
          "value" : "dark"
        }
      ],
      "filename" : "AppIcon-dark.png",
      "idiom" : "universal",
      "platform" : "ios",
      "size" : "1024x1024"
    },
    {
      "appearances" : [
        {
          "appearance" : "luminosity",
          "value" : "tinted"
        }
      ],
      "filename" : "AppIcon-tinted.png",
      "idiom" : "universal",
      "platform" : "ios",
      "size" : "1024x1024"
    }
  ],
  "info" : {
    "author" : "xcode",
    "version" : 1
  }
}
JSON

echo "make-icon.sh: wrote 3 appearances into ZenTomato/Resources/Assets.xcassets/AppIcon.appiconset/"
