#!/usr/bin/env bash
#
# Draw the ZenTomato app icon and write it into the asset catalog.
#
# WHY THE ICON IS DRAWN BY A SCRIPT
# This repository is public and GPL-3.0, which means everything it ships has to
# be something it can license onward. A stock photograph cannot be: the one
# originally chosen was an Unsplash+ image, whose licence is explicitly
# non-transferable and non-sublicensable, so putting it here would have made the
# repository's own licence a promise it could not keep.
#
# Drawing the icon instead makes it original work, GPL-clean, and — because the
# colours below are the Civic Data design tokens the app already uses — it makes
# the icon and the interface the same design rather than two that merely coexist.
#
# The vector source is the truth; the PNGs are build products of this script.
# Re-run it after any change:
#
#     ./Design/icon/make-icon.sh
#
# Needs `rsvg-convert` (brew install librsvg). It is NOT part of the build or of
# CI — the PNGs it produces are committed, so a clone builds without it.

set -euo pipefail

REPO_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)"
HERE="${REPO_ROOT}/Design/icon"
ICONSET="${REPO_ROOT}/ZenTomato/Resources/Assets.xcassets/AppIcon.appiconset"

command -v rsvg-convert >/dev/null 2>&1 || {
  echo "make-icon.sh: rsvg-convert is not installed." >&2
  echo "              brew install librsvg" >&2
  exit 1
}

mkdir -p "$HERE" "$ICONSET"

# --- The drawing -----------------------------------------------------------
# One tomato, flat, filling the frame. Three decisions worth stating:
#
#   NO GLOSS. An earlier pass had a highlight ellipse and it read as sticker
#   shine — wrong for a design language whose whole personality is flat shapes
#   and 2-6px corners. A shaded crescent was tried too and read as a second
#   overlapping circle rather than as form. Flat is the confident answer.
#
#   NO TIMER RING. A countdown ring around the tomato was legible at 1024px and
#   mush at 40px, which is the size that decides whether an icon works. The app
#   is called ZenTomato and a Pomodoro *is* a tomato; the fruit carries it.
#
#   STRAIGHT-EDGED CALYX. Five flat leaves with straight edges rather than an
#   organic curve. It is what stops this reading as a generic fruit sticker, and
#   it is the design system's geometry applied to something that is not a
#   rectangle.
# The enso is generated rather than hand-written: an SVG stroke cannot vary in
# width, so the brush is built as a FILLED outline — walk the outer edge of the
# stroke forward, the inner edge back — with the width tapering toward both ends
# so it reads as a brush lifting off rather than as a pipe.
enso_path() {
  python3 - "$@" <<'PYEOF'
import math, sys
cx, cy, R, start_deg, sweep_deg, w_max = (float(a) for a in sys.argv[1:7])
STEPS = 120

def width(t):
    # Fat through the middle, thin at the ends; the exit is left slightly
    # heavier than the entry, which is what a real brush stroke does.
    taper = math.sin(math.pi * t) ** 0.62
    return w_max * (0.10 + 0.90 * taper) * (0.82 + 0.30 * t)

outer, inner = [], []
for i in range(STEPS + 1):
    t = i / STEPS
    a = math.radians(start_deg + sweep_deg * t)
    # A very slight wobble in the radius. A mathematically perfect circle reads
    # as machined, which is the opposite of what an enso is.
    r = R * (1 + 0.010 * math.sin(t * 5.1 + 0.7) - 0.006 * math.cos(t * 2.3))
    hw = width(t) / 2
    outer.append((cx + (r + hw) * math.cos(a), cy + (r + hw) * math.sin(a)))
    inner.append((cx + (r - hw) * math.cos(a), cy + (r - hw) * math.sin(a)))

pts = outer + inner[::-1]
print("M %.1f %.1f " % pts[0] + " ".join("L %.1f %.1f" % q for q in pts[1:]) + " Z")
PYEOF
}

draw() {
  local out="$1" ground="$2" body="$3" calyx="$4" stem="$5" ring="$6"
  local ring_d
  ring_d="$(enso_path 512 512 384 -118 344 90)"
  cat > "${HERE}/${out}.svg" <<SVG
<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024">
  <!-- Generated by Design/icon/make-icon.sh — edit that, not this. -->
  <rect width="1024" height="1024" fill="${ground}"/>
  <path d="${ring_d}" fill="${ring}"/>
  <circle cx="512" cy="574" r="246" fill="${body}"/>
  <g fill="${calyx}" transform="translate(0,266) scale(0.70) translate(219.4,0)">
    <path d="M 512 150 L 512 300 L 350 236 Z"/>
    <path d="M 512 150 L 512 300 L 674 236 Z"/>
    <path d="M 512 176 L 512 316 L 386 356 Z"/>
    <path d="M 512 176 L 512 316 L 638 356 Z"/>
    <path d="M 512 196 L 452 330 L 512 344 L 572 330 Z"/>
  </g>
  <rect x="497" y="277" width="30" height="76" rx="5" fill="${stem}"/>
</svg>
SVG
  rsvg-convert -w 1024 -h 1024 "${HERE}/${out}.svg" -o "${ICONSET}/${out}.png"
}

# Colours are Civic Data tokens, the same values ZenTomato/DesignSystem uses.
#
# Two elements sit on two different grounds, and that decides which of them
# flips between the themes:
#
#   THE RING sits on the page, so it must flip. sage500 reads on stone; on slate
#   it would sink, so dark takes sage400 — the same one-step lift the app's dark
#   theme applies to every accent, and for the same reason.
#
#   THE CALYX sits on the tomato, which is red in both themes, so it does NOT
#   flip. It stays sage700 in both. An earlier pass lightened it along with
#   everything else and the result inverted: in dark the calyx came out lighter
#   than the ring, reversing the relationship the light icon establishes.
#
#   TINTED is greyscale. iOS derives the user's chosen tint from luminance, so
#   this variant carries no hue of its own; the values are spaced so the ring,
#   body and calyx still separate once a single hue is applied.
draw AppIcon-light  "#f6f5f2" "#c0392b" "#4c5c36" "#3f4c2d" "#667a49"
draw AppIcon-dark   "#1c1f22" "#e06a50" "#4c5c36" "#3f4c2d" "#8aa163"
draw AppIcon-tinted "#ffffff" "#7d7d7d" "#242424" "#1a1a1a" "#4a4a4a"

# --- The catalog entry -----------------------------------------------------
#
# FOUR ENTRIES, NOT THREE: three iOS appearances and one for watchOS.
#
# The watch app draws its icon from this same catalog, and an entry is matched by
# PLATFORM — so the three `"platform" : "ios"` entries below are invisible to
# watchOS however correct they look. Without the fourth the watch app installs
# with no icon at all and nothing reports a problem: there is no build warning,
# because an app icon is not required to build.
#
# watchOS takes the light artwork and has no dark or tinted appearance of its
# own, which is why one entry covers it.
cat > "${ICONSET}/Contents.json" <<'JSON'
{
  "images" : [
    {
      "filename" : "AppIcon-light.png",
      "idiom" : "universal",
      "platform" : "ios",
      "size" : "1024x1024"
    },
    {
      "filename" : "AppIcon-light.png",
      "idiom" : "universal",
      "platform" : "watchos",
      "size" : "1024x1024"
    },
    {
      "appearances" : [
        {
          "appearance" : "luminosity",
          "value" : "dark"
        }
      ],
      "filename" : "AppIcon-dark.png",
      "idiom" : "universal",
      "platform" : "ios",
      "size" : "1024x1024"
    },
    {
      "appearances" : [
        {
          "appearance" : "luminosity",
          "value" : "tinted"
        }
      ],
      "filename" : "AppIcon-tinted.png",
      "idiom" : "universal",
      "platform" : "ios",
      "size" : "1024x1024"
    }
  ],
  "info" : {
    "author" : "xcode",
    "version" : 1
  }
}
JSON

echo "make-icon.sh: wrote 3 iOS appearances and the watchOS icon into ZenTomato/Resources/Assets.xcassets/AppIcon.appiconset/"
