#!/usr/bin/env python3
"""Generate docs/plans/00-status.md — the state of the project as one page.

WHY THIS EXISTS. The page it writes carried this header for the life of the
project:

    <!-- GENERATED by scripts/gen_status.py - do not edit by hand. -->

and this file did not exist. Not in the working tree, not in 350 commits, not in
any branch, and nothing in .github/ or scripts/ or .githooks/ referenced it. So
the project's single status artifact was hand-written prose wearing a generated
file's header, telling every reader not to correct it. It reported F8 as "plan
written, awaiting the gate. No code has been written" for six days while six F8
commits sat on main, and nothing was ever going to notice. Filed as O42.

WHAT IT MAY READ, AND WHAT IT MAY NOT. Everything here comes from the register,
the plan headers and the specs. NOTHING COMES FROM GIT AND THERE IS NO DATE - a
generated file that embeds anything moving on its own can never compare equal to
a regeneration of itself, and --check would then fail for reasons nobody caused.
A prior project's page reported which task IDs had appeared in a commit scope, so
the commit that shipped F3-T1 was the thing that made F3-T1 appear: the page was
stale by the act of committing it.

WHAT IT REFUSES TO GUESS. Where a source says nothing, the page says nothing -
"-" for an absent field, `unknown` for an absent status. `unknown` is not a third
kind of open; it means the source was silent and the row is a question for the
owner. The failure this guards against is the register parser that returned
title='ratified' for every row while fifteen assertions passed, and a status page
that reported `open` for rows nobody had given a status.

USAGE
    python3 scripts/gen_status.py           # write the page
    python3 scripts/gen_status.py --check   # exit 1 if the page is out of date
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REGISTER = ROOT / "docs/plans/00-register.md"
STATUS = ROOT / "docs/plans/00-status.md"
PLANS_DIR = ROOT / "docs/plans"
CHORES_DIR = ROOT / "docs/chores"
SPECS_DIR = ROOT / "docs/specs"

PROJECT = "ZenTomato"

# A status that means the row is finished. Everything else that is not blank is
# open - `proposed` included, because a proposed decision is outstanding work.
CLOSED = {"closed", "done", "struck", "superseded", "rejected", "abandoned"}

# The registers conventions.md names, in the order it names them. A register
# with no rows still gets a line, so that "we have no risk register" is visible
# rather than absent.
# ("A", "Agent items") is APPENDED and not inserted. A known register always
# gets a line, and A currently sorts last as an "extra", so appending leaves
# every existing row of the generated table exactly where it is. It is here
# because without it the page printed `A (`A`)` as the register's own name, on
# a page CI keeps current - the register D36 opened, unnamed. Proved by C33-M4.
KNOWN_REGISTERS = [("D", "Decisions"), ("RR", "Risks"), ("O", "Owner items"),
                   ("H", "Hooks"), ("M", "Mutations"), ("C", "Chores"),
                   ("A", "Agent items")]

# The two registers whose own text says only the owner can close a row.
OWNER_REGISTERS = {"O", "D"}

CELL_LIMIT = 100

# What counts as a register row id, and it is deliberately two shapes rather
# than one. The bare form - O1, D30, RR4 - is what every register used until
# C33. THE SECOND FORM IS THE SCOPED MUTATION ID, F8-M1 or C32-M7, and it is
# here because 81 of this project's 103 mutation ids carry a unit scope and a
# bare-only filter dropped every one of them IN SILENCE: the backfilled
# `## Mutations (M)` section would have reported 22 rows on a page CI keeps
# current, which is the failure D38 opened the register to prevent.
#
# The two alternatives were refused and are named so they are not re-proposed.
# Renumbering the scoped ids into a global sequence breaks citations in shipped
# Swift - ShapeSeamTests, ShapeScreenTests, ShapeStore.swift and four more cite
# `F8-M<n>` by name - and conventions.md forbids it outright: an identifier, not
# an index. Putting a synthetic bare id in the ID column invents identifiers
# nothing cites.
#
# The trailing `[a-z]?` on the mutation number is the retrofit letter, and it is
# here because C32-M4b exists: conventions.md allows a letter on an identifier
# and the population already uses one. Without it that row would have been
# dropped in silence, which is the same defect one character over.
#
# IT IS WIDENED BY EXACTLY ONE ALTERNATIVE AND NO MORE. A filter that accepted
# any hyphenated token would count `MUTATION-X`, and a widening that counts
# anything is not a filter. C33-M3 is the mutation that pins that half.
ROW_ID = re.compile(r"[A-Z]{1,2}\d+|[A-Z]{1,2}\d+[a-z]?-M\d+[a-z]?")


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def one_line(text: str, limit: int = CELL_LIMIT) -> str:
    """Collapse to a single table-safe cell.

    Three things, each of which has bitten this page. Pipes are escaped, because
    an unescaped one silently ends the cell and shifts every column after it.
    Whitespace is collapsed, because a Status that wraps across source lines
    otherwise breaks the row in half. And truncation is on a word boundary with
    an ellipsis, because the previous page cut F11's status mid-word at a full
    stop inside bold - "plan written, **awaiting the gate" - which reads as a
    status rather than as damage.
    """
    text = re.sub(r"\s+", " ", text).strip()
    text = text.replace("|", r"\|")
    if len(text) <= limit:
        return text
    cut = text[:limit].rsplit(" ", 1)[0].rstrip(" ,;:-")
    return cut + "…"


def parse_tables(md: str) -> list[tuple[str, list[dict[str, str]]]]:
    """Return [(section heading, [row dicts])] for every '## ' section.

    Rows are keyed by the table's own header cells, so a column added or renamed
    upstream does not silently map onto the wrong field - the lookup misses and
    the value is empty, which the page renders as unknown rather than as a
    confident wrong answer.
    """
    sections: list[tuple[str, list[dict[str, str]]]] = []
    heading = ""
    header: list[str] | None = None
    rows: list[dict[str, str]] = []

    for line in md.splitlines():
        if line.startswith("## "):
            if heading:
                sections.append((heading, rows))
            heading, header, rows = line[3:].strip(), None, []
            continue
        if not line.lstrip().startswith("|"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if all(set(c) <= {"-", ":"} and c for c in cells):
            continue  # the |---|---| separator
        if header is None:
            header = [c.strip("* ").lower() for c in cells]
            continue
        rows.append({header[i]: cells[i] for i in range(min(len(header), len(cells)))})

    if heading:
        sections.append((heading, rows))
    return sections


def register_rows() -> dict[str, list[dict[str, str]]]:
    """Map a register symbol to its rows, taken from the section heading.

    The symbol comes from the heading's own parenthesis - '## Owner items (O)' -
    and not from the IDs inside, so a section whose rows were mis-prefixed is
    visible as a section with the wrong rows rather than quietly redistributed.
    """
    out: dict[str, list[dict[str, str]]] = {}
    for heading, rows in parse_tables(read(REGISTER)):
        m = re.search(r"\(([A-Z]{1,2})\)\s*$", heading)
        if not m or not rows:
            continue
        out.setdefault(m.group(1), []).extend(
            r for r in rows if ROW_ID.fullmatch(r.get("id", ""))
        )
    return out


def status_of(row: dict[str, str]) -> str:
    s = row.get("status", "").strip().lower()
    return s if s else "unknown"


def is_open(row: dict[str, str]) -> bool:
    s = status_of(row)
    return s != "unknown" and s not in CLOSED


def plan_status(path: Path) -> str:
    """The unit's own declared status, or '' when the plan header is silent.

    Reads from '**Status:**' to the next '**Key:**' line or blank line, so a
    status written across several lines - as F8's is - arrives whole rather than
    truncated at the first newline.
    """
    lines = read(path).splitlines()
    for i, line in enumerate(lines):
        if not line.startswith("**Status:**"):
            continue
        parts = [line[len("**Status:**"):]]
        for nxt in lines[i + 1:]:
            if not nxt.strip() or re.match(r"^\*\*[A-Z][^*]*:\*\*", nxt):
                break
            parts.append(nxt)
        return " ".join(parts).strip()
    return ""


def unit_files() -> list[tuple[str, str, Path]]:
    """Every unit that has a plan file, as (id, kind, path), sorted structurally."""
    units: list[tuple[str, str, Path]] = []
    for path in sorted(PLANS_DIR.glob("F*.md")):
        m = re.fullmatch(r"(F\d+[a-z]?)(?:-contract)?", path.stem)
        if m and "-contract" not in path.stem:
            units.append((m.group(1), "feature", path))
    for path in sorted(CHORES_DIR.glob("C*.md")):
        if re.fullmatch(r"C\d+", path.stem):
            units.append((path.stem, "chore", path))
    return sorted(units, key=lambda u: sort_key(u[0]))


def sort_key(unit_id: str) -> tuple[str, int, str]:
    m = re.fullmatch(r"([A-Z]+)(\d+)([a-z]?)", unit_id)
    return (m.group(1), int(m.group(2)), m.group(3)) if m else (unit_id, 0, "")


def task_count(unit_id: str, path: Path) -> int:
    return len(set(re.findall(rf"\b{re.escape(unit_id)}-T(\d+)\b", read(path))))


def vision() -> tuple[str, str]:
    """(sentence, source file) - or ('', '') when no spec declares one.

    Looks only under a '## The vision sentence' heading. The page this replaces
    printed SPEC.md's '**Status:** DRAFT for ratification…' line under that
    header, which is not a vision sentence and never was; a wrong answer under a
    confident label is worse than an absent one, because nobody re-checks it.
    """
    for path in sorted(SPECS_DIR.glob("*.md")):
        lines = read(path).splitlines()
        for i, line in enumerate(lines):
            if not re.match(r"^##\s+The vision sentence", line):
                continue
            quote = [ln.lstrip("> ").strip() for ln in lines[i + 1:i + 8]
                     if ln.startswith(">")]
            if quote:
                return " ".join(q for q in quote if q), path.name
    return "", ""


def build() -> str:
    regs = register_rows()
    units = unit_files()
    out: list[str] = []
    w = out.append

    w("<!-- GENERATED by scripts/gen_status.py — do not edit by hand. -->")
    w("<!-- Regenerate: python3 scripts/gen_status.py   ·   CI: python3 scripts/gen_status.py --check -->")
    w("")
    w(f"# Status — {PROJECT}")
    w("")
    w("Generated from `docs/plans/00-register.md`, the plan files in `docs/plans/` and `docs/chores/`, "
      "and the specs in `docs/specs/`, by `scripts/gen_status.py`. Hand edits are reverted by the next "
      "run and fail CI in the meantime.")
    w("")
    w("**Nothing on this page comes from git, and there is no date.** A generated file that embeds "
      "anything which moves on its own can never compare equal to a regeneration of itself — `--check` "
      "would then fail for a reason nobody caused. A prior project's page reported which task IDs had "
      "appeared in a commit scope, so the commit that first shipped `F3-T1` was the thing that made "
      "`F3-T1` appear: the page was stale by the act of committing it. Everything here derives from the "
      "register, the plan headers and the specs, so it changes only when they change, and regenerating "
      "is part of that same edit.")
    w("")

    w("## The vision sentence")
    w("")
    sentence, src = vision()
    if sentence:
        w(f"> {sentence}")
        w("")
        w(f"From `docs/specs/{src}`.")
    else:
        w("**No spec in `docs/specs/` declares one under a `## The vision sentence` heading.** This page "
          "will not substitute a nearby line for it — the page it replaced printed `SPEC.md`'s "
          "`**Status:**` line here, which is not a vision sentence, and a wrong answer under a confident "
          "label is worse than an absent one.")
    w("")

    w("## Features and chores")
    w("")
    w("Status is what the unit's own plan file declares. What has landed in git is deliberately not "
      "here — see the note above. A unit whose plan header is silent shows `—`, which means the plan "
      "did not say, not that the work has not started.")
    w("")
    w("| ID | Kind | Status | Plan | Tasks |")
    w("|---|---|---|---|---|")
    for unit_id, kind, path in units:
        st = plan_status(path)
        rel = path.relative_to(ROOT)
        w(f"| {unit_id} | {kind} | {one_line(st) if st else '—'} | `{rel}` | "
          f"{task_count(unit_id, path)} planned |")
    w("")

    w("## Registers")
    w("")
    w("Counted from `docs/plans/00-register.md`. A register with no rows still gets a line, so that "
      "*\"this project has no risk register\"* is visible rather than absent.")
    w("")
    w("| Register | Rows | Open | Unknown | Closed |")
    w("|---|---|---|---|---|")
    extra = [(s, s) for s in sorted(regs) if s not in {k for k, _ in KNOWN_REGISTERS}]
    for sym, name in KNOWN_REGISTERS + extra:
        rows = regs.get(sym, [])
        unknown = sum(1 for r in rows if status_of(r) == "unknown")
        closed = sum(1 for r in rows if status_of(r) in CLOSED)
        w(f"| {name} (`{sym}`) | {len(rows)} | {sum(1 for r in rows if is_open(r))} | "
          f"{unknown} | {closed} |")
    w("")
    w("`Unknown` is not a third kind of open. It means the source document said nothing about status, "
      "so this page will not guess — the row is a question for the owner.")
    w("")

    w("### By status")
    w("")
    w("| Register | Status | Count |")
    w("|---|---|---|")
    for sym, _ in KNOWN_REGISTERS + extra:
        tally: dict[str, int] = {}
        for row in regs.get(sym, []):
            tally[status_of(row)] = tally.get(status_of(row), 0) + 1
        for st in sorted(tally):
            w(f"| `{sym}` | {st} | {tally[st]} |")
    w("")

    hooks = regs.get("H", [])
    built = sum(1 for h in hooks if status_of(h) in CLOSED)
    w("## Hooks")
    w("")
    w(f"**{built} of {len(hooks)} built.** Prose is advisory; hooks are not. A hook's status is what the "
      "register says — this page does not go looking in `scripts/` for a file and infer that the hook "
      "works, because a file existing is not evidence that it has ever failed.")
    w("")
    w("| ID | Hook | Status |")
    w("|---|---|---|")
    for h in hooks:
        w(f"| {h.get('id', '')} | {one_line(h.get('title', ''))} | {status_of(h)} |")
    w("")

    w("## Open, and owned by whom")
    w("")
    w("Every open row in the register. Owner is `owner` for the two registers whose own text says only "
      "the owner can close a row, and `unassigned` everywhere else — an open item nobody owns is a "
      "finding, not something to paper over with a default.")
    w("")
    w("| Owner | ID | P | Status | Item |")
    w("|---|---|---|---|---|")
    total = 0
    for sym, _ in KNOWN_REGISTERS + extra:
        for row in sorted((r for r in regs.get(sym, []) if is_open(r)),
                          key=lambda r: sort_key(r["id"])):
            total += 1
            who = "owner" if sym in OWNER_REGISTERS else "unassigned"
            w(f"| {who} | {row['id']} | {row.get('p', '—') or '—'} | {status_of(row)} | "
              f"{one_line(row.get('title', ''), 70)} |")
    w("")
    w("---")
    w("")
    w(f"{total} open register rows.")
    w("")
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the committed page is not what this run produces")
    args = ap.parse_args()

    fresh = build()
    if not args.check:
        STATUS.write_text(fresh, encoding="utf-8")
        print(f"gen_status.py: wrote {STATUS.relative_to(ROOT)}")
        return 0

    current = read(STATUS)
    if current == fresh:
        print("gen_status.py: OK — 00-status.md is up to date.")
        return 0
    print("gen_status.py: FAIL — 00-status.md is out of date or hand-edited.", file=sys.stderr)
    print("  Regenerate with: python3 scripts/gen_status.py", file=sys.stderr)
    import difflib
    diff = list(difflib.unified_diff(current.splitlines(), fresh.splitlines(),
                                     "committed", "regenerated", lineterm="", n=1))
    for line in diff[:40]:
        print("  " + line, file=sys.stderr)
    if len(diff) > 40:
        print(f"  … {len(diff) - 40} more diff lines", file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
